### ISSUE TITLE
PoE Site unavailable or Account/Character invalid

### ISSUE THREAD

**Issue by akaAMAZING** [shrewdlogarithm/PoE-Character-Log-PS#1]
Hi there @shrewdlogarithm ,

First of all, thank you so much for this great tool - shall be utilizing this for my build guides going forward.

However, I do seem to be hitting a brick wall when it comes to what to edit. The instructions do seem clear but it seems like I am making a mistake somewhere?

I was attempting to run the tool to track Zizaran as a test and while it was pulling his info from adding his character (ZizaranBurnTheWorld) to "run_chars.ps1" - I seem to be at a loss with where I should be adding it in "scan_chars.ps1". No matter what I edit, I get the same constant message: "PoE Site unavailable or Account/Character invalid".

Again, while it still somehow works and data is logged, I would like to be sure I am following your instructions 100% accurately as to not mess anything up.

Any ideas on how to rectify this behavior?

Would it be possible to add screenshots of what I should be editing? For example if I wanted to track the accounts of Zizaran and Cutedog_ and then another one for if I only wanted to track two specific characters they were playing (Zizaran1 and Cutedog1_).

Thank you so much!

**Comment by akaAMAZING** [comment]
Upon further investigation I assume that the README is outdated and that only the "run_*.ps1" need to be edited with the respected account/character names.

Please correct me if I am wrong.

Thank you!

**Comment by shrewdlogarithm** [comment]
Yes, you only need to edit the run*.ps1 files - and only the one you wish to use.

So to scan whole account(s) edit run_account.ps1 wheras to scan specific characters, edit run_chars.ps1 instead 

I've also updated the README to be a BIT more clear and to reference the Python version which is also now available
